// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Order.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderRequest struct {
	OrderMain            *OrderMain `protobuf:"bytes,1,opt,name=order_main,json=orderMain,proto3" json:"order_main,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OrderRequest) Reset()         { *m = OrderRequest{} }
func (m *OrderRequest) String() string { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()    {}
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098924d90c513ae, []int{0}
}

func (m *OrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderRequest.Unmarshal(m, b)
}
func (m *OrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderRequest.Marshal(b, m, deterministic)
}
func (m *OrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderRequest.Merge(m, src)
}
func (m *OrderRequest) XXX_Size() int {
	return xxx_messageInfo_OrderRequest.Size(m)
}
func (m *OrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderRequest proto.InternalMessageInfo

func (m *OrderRequest) GetOrderMain() *OrderMain {
	if m != nil {
		return m.OrderMain
	}
	return nil
}

type OrderResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098924d90c513ae, []int{1}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *OrderResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*OrderRequest)(nil), "services.OrderRequest")
	proto.RegisterType((*OrderResponse)(nil), "services.OrderResponse")
}

func init() {
	proto.RegisterFile("Order.proto", fileDescriptor_a098924d90c513ae)
}

var fileDescriptor_a098924d90c513ae = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4a, 0xc4, 0x40,
	0x10, 0x45, 0xc9, 0x80, 0xa3, 0xd3, 0x51, 0x06, 0x5a, 0x18, 0x43, 0x50, 0x18, 0xe2, 0x66, 0x56,
	0x09, 0xc6, 0x9d, 0x3b, 0x75, 0x3d, 0x28, 0xf1, 0x00, 0x52, 0x26, 0x45, 0x68, 0x98, 0xe9, 0x8a,
	0x55, 0x9d, 0x1c, 0xc0, 0x2b, 0x78, 0x34, 0xaf, 0xe0, 0x41, 0xc4, 0x4e, 0x07, 0x45, 0x77, 0xf5,
	0x3f, 0x9f, 0xc7, 0xff, 0xa5, 0xe2, 0x07, 0x6e, 0x90, 0xf3, 0x8e, 0xc9, 0x91, 0x3e, 0x12, 0xe4,
	0xc1, 0xd4, 0x28, 0xe9, 0x79, 0x4b, 0xd4, 0xee, 0xb0, 0x80, 0xce, 0x14, 0x60, 0x2d, 0x39, 0x70,
	0x86, 0xac, 0x8c, 0xb9, 0x74, 0xf9, 0xc8, 0xd4, 0x6c, 0xa9, 0xc1, 0xdd, 0x68, 0x64, 0x77, 0xea,
	0xd8, 0x73, 0x2a, 0x7c, 0xed, 0x51, 0x9c, 0x2e, 0x95, 0xa2, 0x6f, 0xfd, 0xbc, 0x07, 0x63, 0x93,
	0x68, 0x1d, 0x6d, 0xe2, 0xf2, 0x34, 0x9f, 0xe8, 0xb9, 0xcf, 0x6e, 0xc1, 0xd8, 0x6a, 0x41, 0xd3,
	0x99, 0xdd, 0xaa, 0x93, 0xc0, 0x90, 0x8e, 0xac, 0xa0, 0x5e, 0xa9, 0xb9, 0x38, 0x70, 0xbd, 0x78,
	0xc0, 0x41, 0x15, 0x94, 0x4e, 0xd4, 0xe1, 0x1e, 0x45, 0xa0, 0xc5, 0x64, 0xb6, 0x8e, 0x36, 0x8b,
	0x6a, 0x92, 0x25, 0x87, 0x39, 0x4f, 0xc8, 0x03, 0xb2, 0xae, 0x55, 0x7c, 0xcf, 0x08, 0x0e, 0xbd,
	0xa9, 0x57, 0x7f, 0x0a, 0x84, 0xb2, 0xe9, 0xd9, 0x3f, 0x7f, 0x2c, 0x90, 0x5d, 0xbe, 0x7d, 0x7c,
	0xbe, 0xcf, 0x2e, 0xb2, 0x65, 0x31, 0x5c, 0x15, 0xf5, 0x0f, 0xe9, 0xe6, 0xd7, 0xb8, 0x97, 0xb9,
	0xff, 0xc0, 0xf5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x88, 0x19, 0x37, 0x49, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderServerClient is the client API for OrderServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServerClient interface {
	CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
}

type orderServerClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServerClient(cc grpc.ClientConnInterface) OrderServerClient {
	return &orderServerClient{cc}
}

func (c *orderServerClient) CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/services.OrderServer/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServerServer is the server API for OrderServer service.
type OrderServerServer interface {
	CreateOrder(context.Context, *OrderRequest) (*OrderResponse, error)
}

// UnimplementedOrderServerServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServerServer struct {
}

func (*UnimplementedOrderServerServer) CreateOrder(ctx context.Context, req *OrderRequest) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}

func RegisterOrderServerServer(s *grpc.Server, srv OrderServerServer) {
	s.RegisterService(&_OrderServer_serviceDesc, srv)
}

func _OrderServer_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServerServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.OrderServer/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServerServer).CreateOrder(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.OrderServer",
	HandlerType: (*OrderServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderServer_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Order.proto",
}
