// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prod.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Area int32

const (
	Area_Area_A Area = 0
	Area_Area_B Area = 1
	Area_Area_C Area = 2
)

var Area_name = map[int32]string{
	0: "Area_A",
	1: "Area_B",
	2: "Area_C",
}

var Area_value = map[string]int32{
	"Area_A": 0,
	"Area_B": 1,
	"Area_C": 2,
}

func (x Area) String() string {
	return proto.EnumName(Area_name, int32(x))
}

func (Area) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_760dc27a66a60a4a, []int{0}
}

type ProdRequest struct {
	ProdId               int32    `protobuf:"varint,1,opt,name=prod_id,json=prodId,proto3" json:"prod_id,omitempty"`
	Area                 Area     `protobuf:"varint,2,opt,name=area,proto3,enum=services.Area" json:"area,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProdRequest) Reset()         { *m = ProdRequest{} }
func (m *ProdRequest) String() string { return proto.CompactTextString(m) }
func (*ProdRequest) ProtoMessage()    {}
func (*ProdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_760dc27a66a60a4a, []int{0}
}

func (m *ProdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdRequest.Unmarshal(m, b)
}
func (m *ProdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdRequest.Marshal(b, m, deterministic)
}
func (m *ProdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdRequest.Merge(m, src)
}
func (m *ProdRequest) XXX_Size() int {
	return xxx_messageInfo_ProdRequest.Size(m)
}
func (m *ProdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProdRequest proto.InternalMessageInfo

func (m *ProdRequest) GetProdId() int32 {
	if m != nil {
		return m.ProdId
	}
	return 0
}

func (m *ProdRequest) GetArea() Area {
	if m != nil {
		return m.Area
	}
	return Area_Area_A
}

type ProdResponse struct {
	ProdStock            int32    `protobuf:"varint,1,opt,name=prod_stock,json=prodStock,proto3" json:"prod_stock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProdResponse) Reset()         { *m = ProdResponse{} }
func (m *ProdResponse) String() string { return proto.CompactTextString(m) }
func (*ProdResponse) ProtoMessage()    {}
func (*ProdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_760dc27a66a60a4a, []int{1}
}

func (m *ProdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdResponse.Unmarshal(m, b)
}
func (m *ProdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdResponse.Marshal(b, m, deterministic)
}
func (m *ProdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdResponse.Merge(m, src)
}
func (m *ProdResponse) XXX_Size() int {
	return xxx_messageInfo_ProdResponse.Size(m)
}
func (m *ProdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProdResponse proto.InternalMessageInfo

func (m *ProdResponse) GetProdStock() int32 {
	if m != nil {
		return m.ProdStock
	}
	return 0
}

type QuerySize struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuerySize) Reset()         { *m = QuerySize{} }
func (m *QuerySize) String() string { return proto.CompactTextString(m) }
func (*QuerySize) ProtoMessage()    {}
func (*QuerySize) Descriptor() ([]byte, []int) {
	return fileDescriptor_760dc27a66a60a4a, []int{2}
}

func (m *QuerySize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySize.Unmarshal(m, b)
}
func (m *QuerySize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySize.Marshal(b, m, deterministic)
}
func (m *QuerySize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySize.Merge(m, src)
}
func (m *QuerySize) XXX_Size() int {
	return xxx_messageInfo_QuerySize.Size(m)
}
func (m *QuerySize) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySize.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySize proto.InternalMessageInfo

func (m *QuerySize) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

// repeaed 修饰符
type ProdStockList struct {
	ProStocks            []*ProdResponse `protobuf:"bytes,1,rep,name=pro_stocks,json=proStocks,proto3" json:"pro_stocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProdStockList) Reset()         { *m = ProdStockList{} }
func (m *ProdStockList) String() string { return proto.CompactTextString(m) }
func (*ProdStockList) ProtoMessage()    {}
func (*ProdStockList) Descriptor() ([]byte, []int) {
	return fileDescriptor_760dc27a66a60a4a, []int{3}
}

func (m *ProdStockList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdStockList.Unmarshal(m, b)
}
func (m *ProdStockList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdStockList.Marshal(b, m, deterministic)
}
func (m *ProdStockList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdStockList.Merge(m, src)
}
func (m *ProdStockList) XXX_Size() int {
	return xxx_messageInfo_ProdStockList.Size(m)
}
func (m *ProdStockList) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdStockList.DiscardUnknown(m)
}

var xxx_messageInfo_ProdStockList proto.InternalMessageInfo

func (m *ProdStockList) GetProStocks() []*ProdResponse {
	if m != nil {
		return m.ProStocks
	}
	return nil
}

func init() {
	proto.RegisterEnum("services.Area", Area_name, Area_value)
	proto.RegisterType((*ProdRequest)(nil), "services.ProdRequest")
	proto.RegisterType((*ProdResponse)(nil), "services.ProdResponse")
	proto.RegisterType((*QuerySize)(nil), "services.QuerySize")
	proto.RegisterType((*ProdStockList)(nil), "services.ProdStockList")
}

func init() {
	proto.RegisterFile("prod.proto", fileDescriptor_760dc27a66a60a4a)
}

var fileDescriptor_760dc27a66a60a4a = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdf, 0x4a, 0x32, 0x41,
	0x18, 0xc6, 0x5d, 0x3f, 0x3f, 0xcb, 0xd7, 0x3f, 0xc9, 0x2b, 0xa5, 0x2c, 0x46, 0x32, 0x47, 0x22,
	0xe4, 0x92, 0xd1, 0x51, 0x07, 0x61, 0x41, 0x61, 0x14, 0x98, 0x5e, 0x80, 0x6c, 0xee, 0x24, 0x43,
	0xb2, 0xb3, 0xcd, 0x8c, 0x42, 0x46, 0x27, 0xdd, 0x42, 0x97, 0xd6, 0x2d, 0x74, 0xdc, 0x35, 0xc4,
	0xcc, 0xac, 0xab, 0x06, 0x1e, 0xed, 0xbb, 0xcf, 0xbe, 0xfb, 0x7b, 0x1e, 0x1e, 0x5e, 0x80, 0x48,
	0xf0, 0xa0, 0x1d, 0x09, 0xae, 0x38, 0xee, 0x4a, 0x2a, 0xe6, 0x6c, 0x4c, 0xa5, 0x5b, 0x9f, 0x70,
	0x3e, 0x99, 0x52, 0xcf, 0x8f, 0x98, 0xe7, 0x87, 0x21, 0x57, 0xbe, 0x62, 0x3c, 0x94, 0x76, 0xcf,
	0xdd, 0xeb, 0x0b, 0x1e, 0xdc, 0xf3, 0x80, 0x4e, 0xad, 0x40, 0x6e, 0x21, 0xaf, 0xa5, 0x01, 0x7d,
	0x99, 0x51, 0xa9, 0xb0, 0x0a, 0x3b, 0x9a, 0x3a, 0x62, 0x41, 0xcd, 0x69, 0x38, 0xcd, 0xff, 0x83,
	0xac, 0x7e, 0xed, 0x05, 0x48, 0x20, 0xe3, 0x0b, 0xea, 0xd7, 0xd2, 0x0d, 0xa7, 0x59, 0xea, 0x94,
	0xda, 0x4b, 0xbf, 0x76, 0x57, 0x50, 0x7f, 0x60, 0xbe, 0x91, 0x63, 0x28, 0x58, 0x96, 0x8c, 0x78,
	0x28, 0x29, 0x1e, 0xda, 0x88, 0x23, 0xa9, 0xf8, 0xf8, 0x39, 0xe6, 0xe5, 0xb4, 0x32, 0xd4, 0x02,
	0x39, 0x82, 0xdc, 0xc3, 0x8c, 0x8a, 0xd7, 0x21, 0x5b, 0x50, 0x44, 0xc8, 0x48, 0xb6, 0xa0, 0xf1,
	0x96, 0x99, 0xc9, 0x35, 0x14, 0xfb, 0xcb, 0xed, 0x3b, 0x26, 0x15, 0x9e, 0x19, 0xa0, 0xe5, 0xc9,
	0x9a, 0xd3, 0xf8, 0xd7, 0xcc, 0x77, 0x0e, 0x56, 0x51, 0xd6, 0xcd, 0x8d, 0x91, 0xf9, 0x53, 0xb6,
	0x5a, 0x90, 0xd1, 0x29, 0x11, 0x20, 0xab, 0x9f, 0xa3, 0x6e, 0x39, 0x95, 0xcc, 0x97, 0x65, 0x27,
	0x99, 0xaf, 0xca, 0xe9, 0xce, 0x8f, 0x63, 0x0b, 0x19, 0x5a, 0x28, 0xfa, 0x50, 0xb8, 0xa1, 0x2a,
	0x89, 0x81, 0xfb, 0x7f, 0xed, 0x4c, 0x6f, 0xee, 0x96, 0x14, 0x84, 0x7c, 0x7c, 0x7d, 0x7f, 0xa6,
	0xeb, 0xe8, 0x7a, 0xf3, 0x13, 0x6f, 0xb2, 0x06, 0xf2, 0xde, 0xe2, 0x9e, 0xdf, 0xf1, 0x02, 0x8a,
	0xeb, 0x16, 0x12, 0x2b, 0x2b, 0x58, 0x52, 0x90, 0x5b, 0xdd, 0x74, 0x48, 0x4a, 0x21, 0x29, 0x3c,
	0x87, 0x7c, 0x0c, 0xe8, 0x85, 0x4f, 0x7c, 0x5b, 0xc4, 0xca, 0xa6, 0x6c, 0x8e, 0x80, 0xa4, 0x1e,
	0xb3, 0xe6, 0x0e, 0x4e, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xed, 0x6d, 0x78, 0xd2, 0x4e, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProdServiceClient is the client API for ProdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProdServiceClient interface {
	GetProdStock(ctx context.Context, in *ProdRequest, opts ...grpc.CallOption) (*ProdResponse, error)
	//返回n个商品库存
	GetProdStocks(ctx context.Context, in *QuerySize, opts ...grpc.CallOption) (*ProdStockList, error)
	GetProdInfo(ctx context.Context, in *ProdRequest, opts ...grpc.CallOption) (*ProdModel, error)
}

type prodServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProdServiceClient(cc grpc.ClientConnInterface) ProdServiceClient {
	return &prodServiceClient{cc}
}

func (c *prodServiceClient) GetProdStock(ctx context.Context, in *ProdRequest, opts ...grpc.CallOption) (*ProdResponse, error) {
	out := new(ProdResponse)
	err := c.cc.Invoke(ctx, "/services.ProdService/GetProdStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prodServiceClient) GetProdStocks(ctx context.Context, in *QuerySize, opts ...grpc.CallOption) (*ProdStockList, error) {
	out := new(ProdStockList)
	err := c.cc.Invoke(ctx, "/services.ProdService/GetProdStocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prodServiceClient) GetProdInfo(ctx context.Context, in *ProdRequest, opts ...grpc.CallOption) (*ProdModel, error) {
	out := new(ProdModel)
	err := c.cc.Invoke(ctx, "/services.ProdService/GetProdInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProdServiceServer is the server API for ProdService service.
type ProdServiceServer interface {
	GetProdStock(context.Context, *ProdRequest) (*ProdResponse, error)
	//返回n个商品库存
	GetProdStocks(context.Context, *QuerySize) (*ProdStockList, error)
	GetProdInfo(context.Context, *ProdRequest) (*ProdModel, error)
}

// UnimplementedProdServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProdServiceServer struct {
}

func (*UnimplementedProdServiceServer) GetProdStock(ctx context.Context, req *ProdRequest) (*ProdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProdStock not implemented")
}
func (*UnimplementedProdServiceServer) GetProdStocks(ctx context.Context, req *QuerySize) (*ProdStockList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProdStocks not implemented")
}
func (*UnimplementedProdServiceServer) GetProdInfo(ctx context.Context, req *ProdRequest) (*ProdModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProdInfo not implemented")
}

func RegisterProdServiceServer(s *grpc.Server, srv ProdServiceServer) {
	s.RegisterService(&_ProdService_serviceDesc, srv)
}

func _ProdService_GetProdStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProdServiceServer).GetProdStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ProdService/GetProdStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProdServiceServer).GetProdStock(ctx, req.(*ProdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProdService_GetProdStocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySize)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProdServiceServer).GetProdStocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ProdService/GetProdStocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProdServiceServer).GetProdStocks(ctx, req.(*QuerySize))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProdService_GetProdInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProdServiceServer).GetProdInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ProdService/GetProdInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProdServiceServer).GetProdInfo(ctx, req.(*ProdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProdService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.ProdService",
	HandlerType: (*ProdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProdStock",
			Handler:    _ProdService_GetProdStock_Handler,
		},
		{
			MethodName: "GetProdStocks",
			Handler:    _ProdService_GetProdStocks_Handler,
		},
		{
			MethodName: "GetProdInfo",
			Handler:    _ProdService_GetProdInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prod.proto",
}
