// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ProdModel.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 商品信息模型
type ProdModel struct {
	ProdId               int32    `protobuf:"varint,1,opt,name=prod_id,json=prodId,proto3" json:"prod_id,omitempty"`
	ProdName             string   `protobuf:"bytes,2,opt,name=prod_name,json=prodName,proto3" json:"prod_name,omitempty"`
	ProdPrice            float32  `protobuf:"fixed32,3,opt,name=prod_price,json=prodPrice,proto3" json:"prod_price,omitempty"`
	ProdKc               int32    `protobuf:"varint,4,opt,name=prod_kc,json=prodKc,proto3" json:"prod_kc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProdModel) Reset()         { *m = ProdModel{} }
func (m *ProdModel) String() string { return proto.CompactTextString(m) }
func (*ProdModel) ProtoMessage()    {}
func (*ProdModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4fdd091ed9136e9, []int{0}
}

func (m *ProdModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdModel.Unmarshal(m, b)
}
func (m *ProdModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdModel.Marshal(b, m, deterministic)
}
func (m *ProdModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdModel.Merge(m, src)
}
func (m *ProdModel) XXX_Size() int {
	return xxx_messageInfo_ProdModel.Size(m)
}
func (m *ProdModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdModel.DiscardUnknown(m)
}

var xxx_messageInfo_ProdModel proto.InternalMessageInfo

func (m *ProdModel) GetProdId() int32 {
	if m != nil {
		return m.ProdId
	}
	return 0
}

func (m *ProdModel) GetProdName() string {
	if m != nil {
		return m.ProdName
	}
	return ""
}

func (m *ProdModel) GetProdPrice() float32 {
	if m != nil {
		return m.ProdPrice
	}
	return 0
}

func (m *ProdModel) GetProdKc() int32 {
	if m != nil {
		return m.ProdKc
	}
	return 0
}

//订单模型
type OrderMain struct {
	OrderId              int32                `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderNum             string               `protobuf:"bytes,2,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	Uid                  int32                `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	OrderMoney           float32              `protobuf:"fixed32,4,opt,name=order_money,json=orderMoney,proto3" json:"order_money,omitempty"`
	OrderTime            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=order_time,json=orderTime,proto3" json:"order_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderMain) Reset()         { *m = OrderMain{} }
func (m *OrderMain) String() string { return proto.CompactTextString(m) }
func (*OrderMain) ProtoMessage()    {}
func (*OrderMain) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4fdd091ed9136e9, []int{1}
}

func (m *OrderMain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderMain.Unmarshal(m, b)
}
func (m *OrderMain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderMain.Marshal(b, m, deterministic)
}
func (m *OrderMain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderMain.Merge(m, src)
}
func (m *OrderMain) XXX_Size() int {
	return xxx_messageInfo_OrderMain.Size(m)
}
func (m *OrderMain) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderMain.DiscardUnknown(m)
}

var xxx_messageInfo_OrderMain proto.InternalMessageInfo

func (m *OrderMain) GetOrderId() int32 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *OrderMain) GetOrderNum() string {
	if m != nil {
		return m.OrderNum
	}
	return ""
}

func (m *OrderMain) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *OrderMain) GetOrderMoney() float32 {
	if m != nil {
		return m.OrderMoney
	}
	return 0
}

func (m *OrderMain) GetOrderTime() *timestamp.Timestamp {
	if m != nil {
		return m.OrderTime
	}
	return nil
}

func init() {
	proto.RegisterType((*ProdModel)(nil), "services.ProdModel")
	proto.RegisterType((*OrderMain)(nil), "services.OrderMain")
}

func init() {
	proto.RegisterFile("ProdModel.proto", fileDescriptor_b4fdd091ed9136e9)
}

var fileDescriptor_b4fdd091ed9136e9 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0x49, 0x67, 0xb7, 0xf6, 0xdd, 0x41, 0xc9, 0xc5, 0x38, 0x91, 0x95, 0x9d, 0x7a, 0xea,
	0x40, 0x4f, 0x7e, 0x04, 0x91, 0xce, 0x11, 0xbc, 0x8f, 0xae, 0x79, 0x1d, 0xc1, 0xa5, 0x29, 0x69,
	0x2b, 0xec, 0x63, 0xf9, 0x0d, 0x47, 0xde, 0xd0, 0xf5, 0x96, 0xe7, 0x4f, 0xde, 0x1f, 0x3c, 0x70,
	0xbf, 0x77, 0x56, 0x95, 0x56, 0xe1, 0xb9, 0x68, 0x9d, 0xed, 0x2d, 0x4f, 0x3a, 0x74, 0x7f, 0xba,
	0xc6, 0x6e, 0xb5, 0x3e, 0x59, 0x7b, 0x3a, 0xe3, 0x96, 0xfc, 0xe3, 0xf0, 0xb3, 0xed, 0xb5, 0xc1,
	0xae, 0xaf, 0x4c, 0x1b, 0xaa, 0x9b, 0x0b, 0xa4, 0xb7, 0xdf, 0xfc, 0x11, 0x16, 0xad, 0xb3, 0xea,
	0xa0, 0x95, 0x60, 0x19, 0xcb, 0x63, 0x39, 0xf7, 0xf2, 0x43, 0xf1, 0x67, 0x48, 0x29, 0x68, 0x2a,
	0x83, 0x22, 0xca, 0x58, 0x9e, 0xca, 0xc4, 0x1b, 0xbb, 0xca, 0x20, 0x7f, 0x01, 0xa0, 0xb0, 0x75,
	0xba, 0x46, 0x31, 0xcb, 0x58, 0x1e, 0x49, 0xaa, 0xef, 0xbd, 0x71, 0x3b, 0xfa, 0x5b, 0x8b, 0xbb,
	0xe9, 0xe8, 0x67, 0xbd, 0xf9, 0x67, 0x90, 0x7e, 0x39, 0x85, 0xae, 0xac, 0x74, 0xc3, 0x9f, 0x20,
	0xb1, 0x5e, 0x4c, 0xf0, 0x05, 0xe9, 0x40, 0x0f, 0x51, 0x33, 0x98, 0x91, 0x4e, 0xc6, 0x6e, 0x30,
	0xfc, 0x01, 0x66, 0x83, 0x56, 0x84, 0x8d, 0xa5, 0x7f, 0xf2, 0x35, 0x2c, 0x43, 0xdd, 0xd8, 0x06,
	0x2f, 0x04, 0x8d, 0x24, 0x90, 0x55, 0x7a, 0x87, 0xbf, 0x43, 0x50, 0x07, 0x3f, 0x86, 0x88, 0x33,
	0x96, 0x2f, 0x5f, 0x57, 0x45, 0x58, 0xaa, 0x18, 0x97, 0x2a, 0xbe, 0xc7, 0xa5, 0x64, 0xa0, 0x7b,
	0x7d, 0x9c, 0x53, 0xfc, 0x76, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x73, 0x91, 0x58, 0xe4, 0x73, 0x01,
	0x00, 0x00,
}
